const menuData = [
  {
    categoryId: "hot-drinks",
    categoryNameEn: "Hot Drinks",
    categoryNameAr: "مشروبات ساخنة",
    items: [
      { nameEn: "Single Turkish Coffee", nameAr: "قهوة تركي سنجل", price: "25" },
      { nameEn: "Double Turkish Coffee", nameAr: "قهوه تركى دبل", price: "35" },
      { nameEn: "French Coffee", nameAr: "قهوة فرنساوى", price: "40" },
      { nameEn: "Hazelnut Coffee", nameAr: "قهوة بندق", price: "40" },
      { nameEn: "Nutella Coffee", nameAr: "قهوة نيوتيلا", price: "40" },
      { nameEn: "Special Coffee", nameAr: "قهوة أسبيشال", price: "35" },
      { nameEn: "Single Espresso", nameAr: "اسبرسو سنجل", price: "35" },
      { nameEn: "Double Espresso", nameAr: "اسبرسو دبل", price: "40" },
      { nameEn: "Espresso Macchiato", nameAr: "اسبرسو ميكاتو", price: "45" },
      { nameEn: "Double Espresso Macchiato", nameAr: "اسبرسو ميكاتو دبل", price: "55" },
      { nameEn: "Cappuccino", nameAr: "كابتشينو", price: "65" },
      { nameEn: "Classic Latte", nameAr: "لاتيه كلاسيك", price: "50" },
      { nameEn: "Americano", nameAr: "أمريكانو", price: "50" },
      { nameEn: "Mocha", nameAr: "موكا", price: "60" },
      { nameEn: "Flat White", nameAr: "فلات ويت", price: "60" },
      { nameEn: "Caramel Macchiato", nameAr: "كارمل ميكاتو", price: "40" },
      { nameEn: "Cortado", nameAr: "كورتادو", price: "45" },
      { nameEn: "Black Nescafe", nameAr: "نسكافيه بلاك", price: "35" },
      { nameEn: "Classic Nescafe", nameAr: "نسكافيه كلاسيك", price: "45" },
      { nameEn: "Nutella Cappuccino", nameAr: " كابيتشنو نوتيلا", price: "50" },
      { nameEn: "White Mocha", nameAr: "وايت موكا", price: "35" },
      { nameEn: "Hot Spanish Latte", nameAr: "هوت اسبانيش لاتيه", price: "60" },
      { nameEn: "Blue Spanish Latte", nameAr: "بلو سبانش", price: "70" },
      { nameEn: "Pistachio Spanish Latte", nameAr: "بستاشيو سبانش", price: "90" },
      { nameEn: "Coffee Mix", nameAr: "كوفي ميكس", price: "20" },
      { nameEn: "Teapot", nameAr: "براد شاي", price: "45" },
      { nameEn: "Anise", nameAr: "ينسون", price: "15" },
      { nameEn: "Hibiscus", nameAr: "كركديه", price: "15" },
      { nameEn: "Hot Lemon", nameAr: "ليمون ساخن", price: "15" },
      { nameEn: "Hot Mint", nameAr: "نعناع ساخن", price: "15" },
      { nameEn: "Tea with Milk", nameAr: "شاي ميلك", price: "20" },
      { nameEn: "Cinnamon with Milk", nameAr: "قرفه ميلك", price: "20" },
      { nameEn: "Flavored Tea", nameAr: "شاى نكهات", price: "15" },
      { nameEn: "Cinnamon", nameAr: "قرفه", price: "20" },
      { nameEn: "Cinnamon with Milk", nameAr: "قرفه ميلك", price: "25" },
      { nameEn: "Ginger", nameAr: "جنزبيل", price: "15" },
      { nameEn: "Herbal Cocktail", nameAr: "كوكتيل اعشاب", price: "30" },
      { nameEn: "Sahlab with Nuts", nameAr: "سحلب مكسرات", price: "40" },
      { nameEn: "Sahlab with Fruits", nameAr: "سحلب فواكه", price: "50" },
      { nameEn: "Hummus", nameAr: "حمص", price: "40" },
      { nameEn: "Hot Chocolate", nameAr: "هوت شوكلت", price: "45" },
      { nameEn: "Hot White Chocolate", nameAr: "هوت وايت شوكلت", price: "45" },
      { nameEn: "Hot Cider", nameAr: "هوت سيدر", price: "45" },
      { nameEn: "Indomie", nameAr: "اندومي", price: "25" },


    ],
  },
  {
    categoryId: "cold-drinks",
    categoryNameEn: "Cold Drinks",
    categoryNameAr: "مشروبات باردة",
    items: [
      { nameEn: "Mango", nameAr: "مانجو", price: "50" },
      { nameEn: "Orange", nameAr: "برتقال ", price: "35" },
      { nameEn: "Strawberry", nameAr: "فراوله ", price: "35" },
      { nameEn: "Guava", nameAr: "جوافه", price: "30" },
      { nameEn: "Lemon", nameAr: "ليمون", price: "35" },
      { nameEn: "Kiwi", nameAr: "كيوي", price: "60" },
      { nameEn: "Avocado", nameAr: "افوكاتو", price: "70" },
      { nameEn: "Banana with Milk", nameAr: "موز بلبن", price: "45" },
      { nameEn: "Strawberry with Milk", nameAr: "فراوله بلبن", price: "50" },
      { nameEn: "Guava with Milk", nameAr: "جوافه بلبن", price: "45" },
      { nameEn: "Lemon with Mint", nameAr: "لمون نعناع", price: "35" },
      { nameEn: "Yogurt with Honey", nameAr: "زبادي عسل", price: "35" },
      { nameEn: "Yogurt with Fruits", nameAr: "زبادي فواكه", price: "45" },
      { nameEn: "Cantaloupe", nameAr: "كنتالوب", price: "40" },
      { nameEn: "Watermelon", nameAr: "بطيخ", price: "45" },
      { nameEn: "Mango Kiwi", nameAr: "مانجو كيوي", price: "60" },
      { nameEn: "Jujube", nameAr: "عناب", price: "30" },
      { nameEn: "Milkshake Caramel", nameAr: "ميلك تشيك كارميل", price: "50" },
      { nameEn: "Milkshake Chocolate", nameAr: "ميلك تشيك شوكليت", price: "50" },
      { nameEn: "Milkshake Lotus", nameAr: "ميلك تشيك لوتس", price: "60" },
      { nameEn: "Milkshake Blueberry", nameAr: "ميلك تشيك بلوبيري", price: "50" },
      { nameEn: "Milkshake Mix Berry", nameAr: "ميلك تشيك ميكس بيري", price: "50" },
      { nameEn: "Milkshake Oreo", nameAr: "ميلك تشيك اوريو", price: "60" },
      { nameEn: "Milkshake Pistachio", nameAr: "ميلك تشيك بستاشيو", price: "95" },
      { nameEn: "Milkshake Boba Po Berry", nameAr: "ميلك تشيك بوبا بو بيري", price: "85" },
      { nameEn: "Milkshake Boba Passion Fruit", nameAr: "ميلك تشيك بوبا باشون فروت", price: "85" },
      { nameEn: "Classic Mojito", nameAr: "كلاسيك موخيتو", price: "65" },
      { nameEn: "Blueberry Mojito", nameAr: "موخيتو بلوبيري", price: "60" },
      { nameEn: "Mix Berry Mojito", nameAr: "موخيتو ميكس بيري", price: "95" },
      { nameEn: "Passion Mojito", nameAr: "موخيتو باشون", price: "70" },
      { nameEn: "Blue Ocean", nameAr: "بلو اوشان", price: "85" },
      { nameEn: "Cherry Cola", nameAr: "شيري كولا ", price: "55" },
      { nameEn: "Sunshine", nameAr: "صن شاين ", price: "70" },
      { nameEn: "Florida", nameAr: "فلوريدا", price: "80" },
      { nameEn: "Pina Colada", nameAr: "بينا كولادا", price: "70" },
      { nameEn: "Level Up Cocktail", nameAr: "كوكتيل تمر حنة ", price: "70" },
      { nameEn: "Fruit Cocktail", nameAr: "فروت كوكتيل", price: "60" },
      { nameEn: "Smoothie Mango", nameAr: "سموزي مانجو", price: "45" },
      { nameEn: "Smoothie Strawberry", nameAr: "سموزي فراوله", price: "35" },



    ],
  },
  {
    categoryId: "soft-drinks",
    categoryNameEn: "Soft Drinks",
    categoryNameAr: "مشروبات غازية",
    items: [
      // Example items, add more below!
      { nameEn: "Pepsi", nameAr: "بيبسي", price: "25" },
      { nameEn: "7 Up", nameAr: "سيفن اب", price: "25" },
      { nameEn: "Miranda", nameAr: "ميريندا", price: "25" },
      { nameEn: "Fayrouz", nameAr: "فييروز", price: "30" },
      { nameEn: "Birell", nameAr: "بيريل", price: "25" },
      { nameEn: "Red Bull", nameAr: "ردبول", price: "75" },
      { nameEn: "Shweppes", nameAr: "شويبس", price: "25" },
      { nameEn: "Sting", nameAr: "ستينج", price: "25" },
      { nameEn: "Twist", nameAr: "تويست", price: "25" },
      { nameEn: "Fiori", nameAr: "فيوري", price: "30" },
      { nameEn: "Water", nameAr: "مياه", price: "10" },
    ],
  },
  {
    categoryId: "dessert",
    categoryNameEn: "Dessert",
    categoryNameAr: "حلويات",
    items: [
      // Example items, add more below!
      { nameEn: "Waffle Nutella", nameAr: "وافل نوتيلا", price: "40" },
      { nameEn: "Waffle White Chocolate", nameAr: "وافل وايت شوكلت", price: "40" },
      { nameEn: "Waffle Lotus", nameAr: "وافل لوتس", price: "40" },
      { nameEn: "Waffle Caramel", nameAr: "وافل كارميل ", price: "40" },
      { nameEn: "Waffle Tamr Henna", nameAr: "وافل تمر حنة ", price: "50" },
      { nameEn: "Fruit Salad", nameAr: "فروت سلاط", price: "50" },
      { nameEn: "2 Ice Cream Scoop", nameAr: "بوله ايس كريم2 ", price: "25" },
      { nameEn: "3 Ice Cream Scoop", nameAr: "3 بوله ايس كريم", price: "35" },
      { nameEn: "Popcorn (Cheese - Salt)", nameAr: "(فشار (جبنه - ملح", price: "20" },
    ],
  },
  {
    categoryId: "hooka",
    categoryNameEn: "Hooka",
    categoryNameAr: "شيشة",
    items: [
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
      { nameEn: "", nameAr: "", price: "" },
    ],
  },
];
